apiVersion: v2
publisher: sample-test
name: sample-java-tests-plugin
version: 0.0.1
type: Theia plugin
displayName: Sample Java Tests Plugin
title: Sample Java Tests Plugin
description: This plug-in runs Java tests against vscode-java inside of your workspace
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/omnisharp-theia-plugin
category: Language
firstPublicationDate: "2020-01-07"
spec:
  extensions:
    - Che_Java_Test_Theia_Plugin.theia
